name: re_tech
description: An e-waste marketplace prototype app
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/iphone.png
    - assets/images/samsung.png
    - assets/images/laptopdell.png
    - assets/images/hplaptop.png
    - assets/images/bluetoothspeaker.png
    - assets/images/playstation.png
    - assets/images/tv.png
